### ISSUE TITLE
Plugin only works when at least one core mark is also set in the blueprint options

### ISSUE THREAD

**Issue by moevbiz** [rasteiner/oh-hi-mark#3]
See title. The plugin only shows the new custom mark button if there's at least one core mark in the settings, i.e
```yml
authors:
  type: writer
  inline: true
  marks:
    - footnote
```
no buttons, but
```yml
authors:
  type: writer
  inline: true
  marks:
    - footnote
    - bold
```
shows both buttons
